### ISSUE TITLE
偶尔会报 SSL 证书错误

### ISSUE THREAD

**Issue by Robotxm** [xenv/jinrishici-sdk-android#1]
在程序第一次访问 API 的时候可能会报 Trust anchor for certification path not found
是不是今日诗词用的证书签发机构默认不被信任的关系呢?

**Comment by xenv** [comment]
我的证书链是完整的，根证书是 DigiCert 的，应该没有信任问题。


可以在这里检查我的接口，安卓是信任该根证书的
https://www.myssl.cn/tools/check-server-cert.html
https://www.ssllabs.com/ssltest/analyze.html?d=v2.jinrishici.com&hideResults=on&latest


我在网上搜索发现
1. 如果手机上面开启了 VPN 的话，可能会有证书问题。
2. 安卓的本地证书库异常，临时绕过可参考 https://stackoverflow.com/questions/42414958/android-java-security-cert-certpathvalidatorexception-trust-anchor-for-certific?r=SearchResults




------------------ 原始邮件 ------------------
发件人: "Robotxm"<notifications@github.com>;
发送时间: 2019年10月24日(星期四) 凌晨0:59
收件人: "xenv/jinrishici-sdk-android"<jinrishici-sdk-android@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [xenv/jinrishici-sdk-android] 偶尔会报 SSL 证书错误 (#1)




在程序第一次访问 API 的时候可能会报 Trust anchor for certification path not found
 是不是今日诗词用的证书签发机构默认不被信任的关系呢?

**Comment by WangHan2014** [comment]
我也遇到了相同的问题，一个真机没问题，相同镜像的两台模拟器轮换报错
![QQ截图20220701144057](https://user-images.githubusercontent.com/53888453/176838936-b12faf5b-3cc6-4a0e-9840-f001a5bb611d.jpg)
上面的证书校验网站提供了这样一个信息
