### ISSUE TITLE
获取诗词时报Socket is closed异常

### ISSUE THREAD

**Issue by guohtime** [xenv/jinrishici-sdk-android#2]
版本：1.4
换成1.3是正常的，没有报错
代码：
![code](https://user-images.githubusercontent.com/44531268/119114507-cf230800-ba58-11eb-9220-2aaacb9bee3e.png)
异常：
![err](https://user-images.githubusercontent.com/44531268/119114682-f1b52100-ba58-11eb-8dab-b43661f04eb2.png)
源码JinrishiciClient类中
![source](https://user-images.githubusercontent.com/44531268/119115097-5cfef300-ba59-11eb-81e7-cfdebbdd2bc8.png)可能是connection关闭时，inputStream也关闭了，在后续的while中读取时就抛出了IO异常

**Comment by xenv** [comment]
这种一般都是全部bod read到内存里面，再做解析的，具体是看编程语言和编程框架了，应该跟我服务器没什么关系



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月21日(周五) 下午5:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [xenv/jinrishici-sdk-android] 获取诗词时报Socket is closed异常 (#2)




 
版本：1.4
 换成1.3是正常的，没有报错
 代码：
 
 异常：
 
 源码JinrishiciClient类中
 可能是connection关闭时，inputStream也关闭了，在后续的while中读取时就抛出了IO异常

**Comment by xenv** [comment]
看错了，我回去再看一下，你也可以帮我看一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月21日(周五) 下午5:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [xenv/jinrishici-sdk-android] 获取诗词时报Socket is closed异常 (#2)




 
版本：1.4
 换成1.3是正常的，没有报错
 代码：
 
 异常：
 
 源码JinrishiciClient类中
 可能是connection关闭时，inputStream也关闭了，在后续的while中读取时就抛出了IO异常

**Comment by xenv** [comment]
看看能不能麻烦你那边帮我看看 1.3 和 1.4 有什么区别，然后提个 PR 上来，我不太会安卓，非常感谢 @guohtime

**Comment by Mystery00** [comment]
我这边抽空看看吧，估计也要花时间去解决jcenter的问题了

**Comment by xenv** [comment]
@Mystery00 看看要不要发个版

**Comment by Mystery00** [comment]
@xenv  后天我弄一下吧，看看是发到maven center还是往jitpack发

**Comment by Mystery00** [comment]
1.5版本已经发布到Maven Central了 @guohtime @xenv 

新版本添加了对自定义HTTP请求框架的支持，具体可以参考README
